### /echo/{msg}
GET http://127.0.0.1:8085/echo/hhhhhh

### /echo
GET http://127.0.0.1:8085/echo?msg=hhhhhhh


### /echo
POST http://127.0.0.1:8085/echo
content-type: application/json

{
  "userName": "zhoujunlin",
  "age": 18
}





